### ISSUE TITLE
Setting up a Module

### ISSUE THREAD

**Issue by charlespeters** [sheetify/sheetify#10]
how would you set up a module to work with sheetify?

**Comment by yoshuawuyts** [comment]
Before anything I'd recommend using [cssnext](https://github.com/cssnext/cssnext) since it has a vibrant ecosystem where `sheetify` doesn't. 

If you're looking to see how to build your own transform take a look at how [sheetify-calc](https://github.com/sheetify/sheetify-calc/blob/master/index.js) and [rework-calc](https://github.com/reworkcss/rework-calc/blob/master/index.js) modify the AST.

If you're looking to consume an existing module, most modules are consumed similar to:
```js
const calc = require('sheetify-calc')
const sheetify = require('sheetify')

sheetify('path/to/my/index.css')
  .transform(calc())
  .bundle()
```

I hope this answers your question!

**Comment by charlespeters** [comment]
i meant more of how do you set up your css modules to work like this: http://sethvincent.com/css-via-npm/#0

**Comment by yoshuawuyts** [comment]
Take a look at [css-wipe](https://github.com/yoshuawuyts/css-wipe)
